apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/location: hel1
  creationTimestamp: "2025-12-09T16:21:21Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
    app.kubernetes.io/instance: hello-world-rest-api
    app.kubernetes.io/managed-by: edka
    app.kubernetes.io/name: hello-world-rest-api
    app.kubernetes.io/version: 0.0.1.RELEASE
    edka.io/account-id: 25c48a5f-bf72-4894-b85d-160843bae941
    edka.io/cluster-id: 66fb93d5-ddd4-4250-bb9b-8e910acd3a90
    edka.io/deployment-id: 66e2f31e-6930-488e-8529-38a8335a8614
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "56006"
  uid: df09b3e4-1494-4600-b8fc-848c2e105f4e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.214.170
  clusterIPs:
  - 10.43.214.170
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30103
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 95.217.170.78
      ipMode: VIP
    - ip: 2a01:4f9:c01e:40d::1
      ipMode: VIP
    - ip: 10.0.0.6
      ipMode: VIP
